### ISSUE TITLE
EnumerateDynamicRecords() throws exception when HasHeaderRecord is false

### ISSUE THREAD

**Issue by Camderman106** [shibayan/CsvHelper.FastDynamic#22]
Steps to reproduce:
`using Stream stream = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
using StreamReader reader = new(stream);
CsvConfiguration cfg = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    HasHeaderRecord = false,
};
using CsvReader csv = new(reader, cfg);
csv.Read();
foreach (var record in csv.EnumerateDynamicRecords())
{
    Console.ReadLine();
}`

Expected behaviour: should return a dynamic record with headers chosen in the same way as standard csv helper library would. That being "Field1", "Field2" etc

I have been able to trace it back to line 27 in the CsvReaderExtensions Class.

The error is simply "System.ArgumentNullException: 'Value cannot be null. (Parameter 'source')'"

**Comment by shibayan** [comment]
Since we now need a header to create dynamic records, we should check the value of HasHeaderRecord.
