### ISSUE TITLE
Invalid Field or Property name

### ISSUE THREAD

**Issue by mortensp** [shibayan/CsvHelper.FastDynamic#8]
I'm trying to read a CSV file from the web where one of the headers contains a space like: "abc efg". I call csvReader.GetDynamicRecords() and the reading proccedes just fine, but I can't access the field named "abc efg" i C# as
it's not an identifier ie. myobject."abc efg" is invalid.

**Comment by shibayan** [comment]
`GetDynamicRecords` returns a dynamic type, but the class implements `IDictionary<string, object>`, so it is an indexer if you cast it.
